createAccount = gideros.class(Sprite)

function createAccount:init()
	local titleBackground = Bitmap.new(Texture.new("images/starsBackground.png"))
	titleBackground:setScale(.5, .5)
	self:addChild(titleBackground)

	local logo = Bitmap.new(Texture.new("images/RcrLogo.png"))
	self:addChild(logo)	
	
	local rect = Shape.new()
	rect:setLineStyle(1, 0x000000, 1)
	rect:setFillStyle(Shape.SOLID, 0xffffff)
	rect:beginPath()
	rect:moveTo(0, 0)
	rect:lineTo(300, 0)
	rect:lineTo(300, 25)
	rect:lineTo(0, 25)
	rect:lineTo(0, 0)
	rect:endPath()
	rect:setPosition(94, 120)
	self:addChild(rect)
	
	local emailInput = TextField.new(font, "email")
	emailInput:setTextColor(0x000000)
	emailInput:setPosition(100, 140)
	emailInput:setScale(2, 2)
	self:addChild(emailInput)
	
	KEYBOARD:registerTextField(emailInput)
	
	local rect2 = Shape.new()
	rect2:setLineStyle(1, 0x000000, 1)
	rect2:setFillStyle(Shape.SOLID, 0xffffff)
	rect2:beginPath()
	rect2:moveTo(0, 0)
	rect2:lineTo(300, 0)
	rect2:lineTo(300, 25)
	rect2:lineTo(0, 25)
	rect2:lineTo(0, 0)
	rect2:endPath()
	rect2:setPosition(94, 155)
	self:addChild(rect2)
	
	local passwordInput = TextField.new(font, "password")
	passwordInput:setTextColor(0x000000)
	passwordInput:setPosition(100, 175)
	passwordInput:setScale(2, 2)
	self:addChild(passwordInput)
	
	KEYBOARD:registerTextField(passwordInput)
		
	local rect3 = Shape.new()
	rect3:setLineStyle(1, 0x000000, 1)
	rect3:setFillStyle(Shape.SOLID, 0xffffff)
	rect3:beginPath()
	rect3:moveTo(0, 0)
	rect3:lineTo(300, 0)
	rect3:lineTo(300, 25)
	rect3:lineTo(0, 25)
	rect3:lineTo(0, 0)
	rect3:endPath()
	rect3:setPosition(94, 190)
	self:addChild(rect3)
	
	local reconfirmInput = TextField.new(font, "reconfirm")
	reconfirmInput:setTextColor(0x000000)
	reconfirmInput:setPosition(100, 210)
	reconfirmInput:setScale(2, 2)
	self:addChild(reconfirmInput)
	
	KEYBOARD:registerTextField(reconfirmInput)
		
	local createButton = Bitmap.new(Texture.new("images/createButton.png"))
	createButton:setScale(.4, .4)
	createButton:setPosition(200, 230)
	
	local createClick = Button.new(createButton, createButton, function() 
		sceneManager:changeScene("mainMenu", 1, SceneManager.crossfade, easing.outBack) 
	end)
	self:addChild(createClick)

end