LUAC = "/Applications/Gideros Studio/Gideros Studio.app/Contents/Tools/luac"

all: .tmp/main.lua.bin .tmp/inputobj.lua.bin .tmp/oldmain.lua.bin .tmp/grid.lua.bin .tmp/player.lua.bin .tmp/runtests.lua.bin .tmp/luaunit.lua.bin .tmp/inputbutton.lua.bin .tmp/inputengine.lua.bin .tmp/collectgame.lua.bin .tmp/button.lua.bin .tmp/list.lua.bin

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/inputobj.lua.bin: inputobj.lua
	$(LUAC) -o ".tmp/inputobj.lua.bin" "inputobj.lua"

.tmp/oldmain.lua.bin: oldmain.lua
	$(LUAC) -o ".tmp/oldmain.lua.bin" "oldmain.lua"

.tmp/grid.lua.bin: grid.lua
	$(LUAC) -o ".tmp/grid.lua.bin" "grid.lua"

.tmp/player.lua.bin: player.lua
	$(LUAC) -o ".tmp/player.lua.bin" "player.lua"

.tmp/runtests.lua.bin: runtests.lua
	$(LUAC) -o ".tmp/runtests.lua.bin" "runtests.lua"

.tmp/luaunit.lua.bin: luaunit.lua
	$(LUAC) -o ".tmp/luaunit.lua.bin" "luaunit.lua"

.tmp/inputbutton.lua.bin: inputbutton.lua
	$(LUAC) -o ".tmp/inputbutton.lua.bin" "inputbutton.lua"

.tmp/inputengine.lua.bin: inputengine.lua
	$(LUAC) -o ".tmp/inputengine.lua.bin" "inputengine.lua"

.tmp/collectgame.lua.bin: collectgame.lua
	$(LUAC) -o ".tmp/collectgame.lua.bin" "collectgame.lua"

.tmp/button.lua.bin: button.lua
	$(LUAC) -o ".tmp/button.lua.bin" "button.lua"

.tmp/list.lua.bin: list.lua
	$(LUAC) -o ".tmp/list.lua.bin" "list.lua"

