LUAC = "/Applications/Gideros Studio/Gideros Studio.app/Contents/Tools/luac"

all: .tmp/textbox.lua.bin .tmp/main.lua.bin .tmp/scenemanager.lua.bin .tmp/easing.lua.bin .tmp/radiobutton.lua.bin .tmp/gameButton.lua.bin .tmp/customButton.lua.bin .tmp/button.lua.bin .tmp/splash.lua.bin .tmp/login.lua.bin .tmp/createAccount.lua.bin .tmp/mainmenu.lua.bin .tmp/gameWait.lua.bin .tmp/gameScreen.lua.bin .tmp/RCRBaseScreen.lua.bin .tmp/acctSettings.lua.bin .tmp/joiningGame.lua.bin .tmp/keyboard.lua.bin .tmp/JSON.lua.bin .tmp/networkadapter.lua.bin .tmp/ltn12.lua.bin .tmp/mime.lua.bin .tmp/socket.lua.bin .tmp/ftp.lua.bin .tmp/url.lua.bin .tmp/tp.lua.bin .tmp/smtp.lua.bin .tmp/http.lua.bin .tmp/util.lua.bin .tmp/sceneObject.lua.bin .tmp/scriptObject.lua.bin .tmp/settings.lua.bin .tmp/RCRBasePopup.lua.bin .tmp/printer.lua.bin .tmp/init.lua.bin

.tmp/textbox.lua.bin: textbox.lua
	$(LUAC) -o ".tmp/textbox.lua.bin" "textbox.lua"

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/scenemanager.lua.bin: scenemanager.lua
	$(LUAC) -o ".tmp/scenemanager.lua.bin" "scenemanager.lua"

.tmp/easing.lua.bin: easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "easing.lua"

.tmp/radiobutton.lua.bin: radiobutton.lua
	$(LUAC) -o ".tmp/radiobutton.lua.bin" "radiobutton.lua"

.tmp/gameButton.lua.bin: gameButton.lua
	$(LUAC) -o ".tmp/gameButton.lua.bin" "gameButton.lua"

.tmp/customButton.lua.bin: customButton.lua
	$(LUAC) -o ".tmp/customButton.lua.bin" "customButton.lua"

.tmp/button.lua.bin: button.lua
	$(LUAC) -o ".tmp/button.lua.bin" "button.lua"

.tmp/splash.lua.bin: splash.lua
	$(LUAC) -o ".tmp/splash.lua.bin" "splash.lua"

.tmp/login.lua.bin: login.lua
	$(LUAC) -o ".tmp/login.lua.bin" "login.lua"

.tmp/createAccount.lua.bin: createAccount.lua
	$(LUAC) -o ".tmp/createAccount.lua.bin" "createAccount.lua"

.tmp/mainmenu.lua.bin: mainmenu.lua
	$(LUAC) -o ".tmp/mainmenu.lua.bin" "mainmenu.lua"

.tmp/gameWait.lua.bin: gameWait.lua
	$(LUAC) -o ".tmp/gameWait.lua.bin" "gameWait.lua"

.tmp/gameScreen.lua.bin: gameScreen.lua
	$(LUAC) -o ".tmp/gameScreen.lua.bin" "gameScreen.lua"

.tmp/RCRBaseScreen.lua.bin: RCRBaseScreen.lua
	$(LUAC) -o ".tmp/RCRBaseScreen.lua.bin" "RCRBaseScreen.lua"

.tmp/acctSettings.lua.bin: acctSettings.lua
	$(LUAC) -o ".tmp/acctSettings.lua.bin" "acctSettings.lua"

.tmp/joiningGame.lua.bin: joiningGame.lua
	$(LUAC) -o ".tmp/joiningGame.lua.bin" "joiningGame.lua"

.tmp/keyboard.lua.bin: keyboard.lua
	$(LUAC) -o ".tmp/keyboard.lua.bin" "keyboard.lua"

.tmp/JSON.lua.bin: JSON.lua
	$(LUAC) -o ".tmp/JSON.lua.bin" "JSON.lua"

.tmp/networkadapter.lua.bin: networkadapter.lua
	$(LUAC) -o ".tmp/networkadapter.lua.bin" "networkadapter.lua"

.tmp/ltn12.lua.bin: http/ltn12.lua
	$(LUAC) -o ".tmp/ltn12.lua.bin" "http/ltn12.lua"

.tmp/mime.lua.bin: http/mime.lua
	$(LUAC) -o ".tmp/mime.lua.bin" "http/mime.lua"

.tmp/socket.lua.bin: http/socket.lua
	$(LUAC) -o ".tmp/socket.lua.bin" "http/socket.lua"

.tmp/ftp.lua.bin: http/socket/ftp.lua
	$(LUAC) -o ".tmp/ftp.lua.bin" "http/socket/ftp.lua"

.tmp/url.lua.bin: http/socket/url.lua
	$(LUAC) -o ".tmp/url.lua.bin" "http/socket/url.lua"

.tmp/tp.lua.bin: http/socket/tp.lua
	$(LUAC) -o ".tmp/tp.lua.bin" "http/socket/tp.lua"

.tmp/smtp.lua.bin: http/socket/smtp.lua
	$(LUAC) -o ".tmp/smtp.lua.bin" "http/socket/smtp.lua"

.tmp/http.lua.bin: http/socket/http.lua
	$(LUAC) -o ".tmp/http.lua.bin" "http/socket/http.lua"

.tmp/util.lua.bin: util.lua
	$(LUAC) -o ".tmp/util.lua.bin" "util.lua"

.tmp/sceneObject.lua.bin: sceneObject.lua
	$(LUAC) -o ".tmp/sceneObject.lua.bin" "sceneObject.lua"

.tmp/scriptObject.lua.bin: scriptObject.lua
	$(LUAC) -o ".tmp/scriptObject.lua.bin" "scriptObject.lua"

.tmp/settings.lua.bin: settings.lua
	$(LUAC) -o ".tmp/settings.lua.bin" "settings.lua"

.tmp/RCRBasePopup.lua.bin: RCRBasePopup.lua
	$(LUAC) -o ".tmp/RCRBasePopup.lua.bin" "RCRBasePopup.lua"

.tmp/printer.lua.bin: printer.lua
	$(LUAC) -o ".tmp/printer.lua.bin" "printer.lua"

.tmp/init.lua.bin: init.lua
	$(LUAC) -o ".tmp/init.lua.bin" "init.lua"

